name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/online-judge-tools/verification-helper.git

   

    # required only if you want to verify Java code
    - name: Install dependencies (Java)
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'

    # required only if you want to verify C# script files
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.413'
    - name: Install dependencies (C#)
      run: dotnet tool install --global dotnet-script --version 1.3.0

    # required only if you want to verify Go code
    - name: Install dependencies (Go)
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.7'

    # required only if you want to verify Ruby code
    - name: Install dependencies (Ruby)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Set up Rust (1.70.0)
      run: |
        rustup set profile minimal
        rustup install 1.70.0
        rustup override set nightly

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
